In [1]:
import numpy as np

In [2]:
a = np.arange(12).reshape(3, 4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [3]:
print(a[1:3, :])#,前面的部分用于检索行，逗号后面的部分用于检索列，相当于图片裁剪

[[ 4  5  6  7]
 [ 8  9 10 11]]


In [4]:
print(a[0, :])   #取出第0行的全部内容

[0 1 2 3]


In [5]:
print(a[:, 1])   #取出第一列

[1 5 9]


In [6]:
print(a[:2, ::2,])  #取出第零行和第一行的偶数列，相当于图片压缩

[[0 2]
 [4 6]]


In [7]:
print(a[1:3,::2])  #取出第一行和第二行的偶数列，相当于图片压缩

[[ 4  6]
 [ 8 10]]


In [8]:
print(a[:, ::-1])  #反序打印数组，相当于图片左右翻转

[[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]]


In [9]:
a = np.arange(36).reshape(6, 6) - 18
print(a)

[[-18 -17 -16 -15 -14 -13]
 [-12 -11 -10  -9  -8  -7]
 [ -6  -5  -4  -3  -2  -1]
 [  0   1   2   3   4   5]
 [  6   7   8   9  10  11]
 [ 12  13  14  15  16  17]]


In [10]:
a = a.astype(float)
print(a)

[[-18. -17. -16. -15. -14. -13.]
 [-12. -11. -10.  -9.  -8.  -7.]
 [ -6.  -5.  -4.  -3.  -2.  -1.]
 [  0.   1.   2.   3.   4.   5.]
 [  6.   7.   8.   9.  10.  11.]
 [ 12.  13.  14.  15.  16.  17.]]


In [11]:
#小于0取绝对值，大于0取对数

In [12]:
for i in range(6):
    for j in range(6):
        if a[i][j] > 0:
            a[i][j] = np.log(a[i][j])
        elif a[i][j] < 0:
            a[i][j] = np.abs(a[i][j])
print(a)

[[18.         17.         16.         15.         14.         13.        ]
 [12.         11.         10.          9.          8.          7.        ]
 [ 6.          5.          4.          3.          2.          1.        ]
 [ 0.          0.          0.69314718  1.09861229  1.38629436  1.60943791]
 [ 1.79175947  1.94591015  2.07944154  2.19722458  2.30258509  2.39789527]
 [ 2.48490665  2.56494936  2.63905733  2.7080502   2.77258872  2.83321334]]


In [13]:
a = np.arange(36).reshape(6, 6) - 18
a = a.astype(float)
print(a)

[[-18. -17. -16. -15. -14. -13.]
 [-12. -11. -10.  -9.  -8.  -7.]
 [ -6.  -5.  -4.  -3.  -2.  -1.]
 [  0.   1.   2.   3.   4.   5.]
 [  6.   7.   8.   9.  10.  11.]
 [ 12.  13.  14.  15.  16.  17.]]


In [14]:
a[a > 0] = np.log(a[a > 0])  #a[a > 0]表明选中数组a中所有元素大于0的部分
a[a < 0] = np.abs(a[a < 0])
print(a)
#这段代码很python

[[18.         17.         16.         15.         14.         13.        ]
 [12.         11.         10.          9.          8.          7.        ]
 [ 6.          5.          4.          3.          2.          1.        ]
 [ 0.          0.          0.69314718  1.09861229  1.38629436  1.60943791]
 [ 1.79175947  1.94591015  2.07944154  2.19722458  2.30258509  2.39789527]
 [ 2.48490665  2.56494936  2.63905733  2.7080502   2.77258872  2.83321334]]
